### ISSUE TITLE
Turning off specific effect?

### ISSUE THREAD

**Issue by HarryJam8** [Feu-Secret/Tokenmagic#1]
Hi Ludovic! First of all I'd like to say I enjoy the Token Magic FX immensely. I been trying to get animated effect for a while now and it is perfect. I want to see if I can combine it with other macros.
For example, I want to have a specific effect when the barbarian enters rage, and another effect when the barbarian uses reckless attacks. While the barbarian will stay in rage for a duration, the reckless attacks is used intermittently.
Is there anyway to turn off a specific effect (e.g. the one combined with reckless attack) instead of relying on the "delete filters on selected/placeable tiles", which removes all the effect present (including the effect I string onto Rage)?

**Comment by HarryJam8** [comment]
Just saw the message on discord, oops!

**Comment by Feu-Secret** [comment]
Hi HarryJam8,
An update is incoming that will allow you to disable or update effects and their values.
Just a few days to wait ;)
