### ISSUE TITLE
Chat Log output issue with Dungeon World System

### ISSUE THREAD

**Issue by Harshmage** [Feu-Secret/Tokenmagic#102]
Token Magic FX 0.4.4
Dungeon World 0.6.9
Foundry VTT 0.7.9

Where output text for Complications (mark XP), Partial Success, and Success, text will read as the object statement instead of the language translation (DW.[object Object]failure, partial, success).

Expected:
![TFX-DW-Expected](https://user-images.githubusercontent.com/1031437/113467672-6b397700-93f9-11eb-83bd-7d73b080070a.png)

Issue:
![TFX-DW-Issue](https://user-images.githubusercontent.com/1031437/113467674-6bd20d80-93f9-11eb-9896-3986da8c4825.png)

**Comment by dev7355608** [comment]
It doesn't look like that this is Token Magic's fault. See my comment [here](https://gitlab.com/asacolips-projects/foundry-mods/dungeonworld/-/issues/61).

**Comment by sanguaire** [comment]
You override the concat handlebars function. 

The original implementation of foundry is

```
  static concat(...values) {
    const options = values.pop();
    const join = options.hash?.join || "";
    return new Handlebars.SafeString(values.join(join));
  }
```

your implementation included in the init hook

```

  // Extracted from https://github.com/leapfrogtechnology/just-handlebars-helpers/
  Handlebars.registerHelper("concat", function(...params) {
    // Ignore the object appended by handlebars.
    if ( typeof params[params.length - 1] === "object" ) {
      params.pop();
    }

    return params.join("");
  });
```

I have the same issue in my own system. Please fix.

**Comment by greedyj4ck** [comment]
Same issue in my system. Users report some issue with disappearing text while using this module.
