### ISSUE TITLE
Override setting inner opacity does not fully render on template

### ISSUE THREAD

**Issue by kandashi** [Feu-Secret/Tokenmagic#103]
Adjustments to the inner opacity of webm files within the overrides section correctly pass through to the template data, but does not correctly render through to the actuall template untill the template config is opened and re-saved.

To replciate:
- Add a webm file to an override and adjust the opacity to any value
- Cast the spell and apply the template
- Open the template config (opacity is correctly set from the override settigns)
- Save config, the opacity will now be correctly applied

**Comment by dev7355608** [comment]
Thanks for the report!
