### ISSUE TITLE
Filters fail to load on demand when Filter caching on Startup is disabled

### ISSUE THREAD

**Issue by MS-PBS** [Feu-Secret/Tokenmagic#110]
If I disable filter caching on startup and then try to apply a filter to a token, the tab freezes for a second (I assume this is because it's trying to load the filter), but then either nothing happens or the token's image disappears. Removing the filter with the appropiate function returns the token's image. This only happens if I disable filter caching on startup.

I've tried this with all other modules disabled (Foundry ver. 0.7.9, TMFX ver. 0.4.4).  I see no error messages or other kind of messages referencing TMFX on the console.

**Comment by Feu-Secret** [comment]
On which system does this happen? MacOS, Windows, Linux?

**Comment by Feu-Secret** [comment]
@MS-PBS Can you retry with the new release please ?

**Comment by MS-PBS** [comment]
Windows, on Brave browser. However,  I think you fixed it in the new release, thank you! I get a short freeze the first time an effect is applied, but that's expected.

Sorry for derailing the thread a little but, but, has a GM always had to be connected for a player to apply filters to tokens they own? I noticed this just now and I can't tell if this behaviour has changed in the new release or if it has always been like this.

**Comment by Feu-Secret** [comment]
> 
> 
> Windows, on Brave browser. However, I think you fixed it in the new release, thank you! I get a short freeze the first time an effect is applied, but that's expected.

Ok perfect. I'm closing the issue.

> 
> Sorry for derailing the thread a little but, but, has a GM always had to be connected for a player to apply filters to tokens they own? I noticed this just now and I can't tell if this behaviour has changed in the new release or if it has always been like this.

It has always been like this.
