### ISSUE TITLE
Incompatibility with enhanced-terrain-layer

### ISSUE THREAD

**Issue by Merudo** [Feu-Secret/Tokenmagic#120]
When running a game with both Tokenmagic and [enhanced-terrain-layer](https://github.com/ironmonk88/enhanced-terrain-layer), I get the following error message:

```
libWrapper: Potential conflict detected between module 'enhanced-terrain-layer' and 'tokenmagic'.
Detected non-libWrapper wrapping of 'game.dnd5e.canvas.AbilityTemplate.fromItem' by 'enhanced-terrain-layer'. This will potentially lead to conflicts.
🎁console_ui @ libWrapper-consts.js:8
```
Could the wrapping of `game.dnd5e.canvas.AbilityTemplate.fromItem` be changed to a libWrapper wrapping?

Error report for `enhanced-terrain-layer`: https://github.com/ironmonk88/enhanced-terrain-layer/issues/17

**Comment by Feu-Secret** [comment]
`game.dnd5e.canvas.AbilityTemplate.fromItem` has been wrapped by enhanced-terrain-layer. I close this issue.
