### ISSUE TITLE
Null object when casting measured template spell with "Enable automatic template effects" checked

### ISSUE THREAD

**Issue by Jumbolaya** [Feu-Secret/Tokenmagic#127]
When casting a spell from the spellbook that requires a measured template being placed, I get the following error in console:

dnd5e.js:185 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at Function.fromItem (dnd5e.js:185)
    at Function.game.dnd5e.canvas.AbilityTemplate.fromItem (dnd5e.js:118)
    at Item5e.roll (entity.js:419)

It only happens when Token Magic FX has "Enable automatic template effects" checked. 0.7.10 Foundry, 1.2.4 DND5e, 0.4.4 TokenMagicFX (happened on 0.4.3 and 0.5.0 too). If I disable this setting, I'm able to place the template just fine. There are no other errors reported in the console.

This happens even when disabling all modules except Token Magic FX.

This was also reported by another user a few months back who never found a resolution. https://discordapp.com/channels/170995199584108546/722566083499786352/820067058754256917

I went ahead and put a break point in the code:

```
function fromItem(wrapped, ...args) {
	const [ item ] = args;
	const template = wrapped(...args);
	if (!template) {
		return template;
	}
	let hasPreset = template.hasOwnProperty("tmfxPreset");
	if (hasPreset) {
		return template;
	}
	const settings = game.settings.get('tokenmagic', 'autoTemplateSettings');
	let updated = fromOverrides(Object.values(settings.overrides), item, template);   <------ TypeError here
	if (!updated) {
		fromCategories(settings.categories, item, template);
	}
	return template;
}
```

The overrides member of "settings" seems to be undefined.

**Comment by Feu-Secret** [comment]
Hi. I cannot reproduce the problem. Tested on 0.7.10 with 0.5.0 TMFX. I need more informations: spells used? From which compendium? Or a custom spell? Need a screenshot of the spell.

**Comment by Jumbolaya** [comment]
I reproduced with multiple spells that used measured templates, but the one I typically test with is Fireball from the Spells (SRD) compendium. Another example would be shatter.

Is there any sort of debug statements/break points I could put in place inside the source code that would help triage?

Here is a screenshot of the fireball spell:

![image](https://user-images.githubusercontent.com/65468850/120092834-b612fa80-c0db-11eb-905a-8491eed67ae2.png)

**Comment by Feu-Secret** [comment]
Reproduced. It happens when there is no overrides set in the automatic template settings. 
Workaround : create a dummy override which will be never used.
