### ISSUE TITLE
Duplicating effects (not sure if this is intended)

### ISSUE THREAD

**Issue by kandashi** [Feu-Secret/Tokenmagic#13]
Reapplying effects with duplicate them. Not sure if this is intended or not. 
![image](https://user-images.githubusercontent.com/1347785/88239762-30355000-cc7d-11ea-8ed1-64793d5fd912.png)
Example of multiple mirror image effects applied one after another.

Would be good to simply overwrite old effect with new parameters :)

**Comment by Feu-Secret** [comment]
This is intended. The same filter can be applied multiple times. Concerning filters API, i will extend it with a `hasFilter`, so that modders can easily get filters information.
