### ISSUE TITLE
Issue with Furnace integration

### ISSUE THREAD

**Issue by arcos** [Feu-Secret/Tokenmagic#134]
With version 2.6.1 of furnace and 0.8.6 I am seeing this error in console when starting a world:

![image](https://user-images.githubusercontent.com/143747/120434294-91897d80-c37c-11eb-94c9-d798c6cb99cb.png)

The line in tokenmagic.js shows:

![image](https://user-images.githubusercontent.com/143747/120434720-196f8780-c37d-11eb-9315-146d44b5d6a9.png)

It looks like, based on the[ README.md](https://github.com/League-of-Foundry-Developers/fvtt-module-furnace/blob/master/README.md) that the Furnace is no longer needed due to updates in 0.8.6. It is probably safe to remove this integration altogether in Tokenmagic.

**Comment by Feu-Secret** [comment]
Thanks for the report.
