### ISSUE TITLE
Animated rotation bugs out on canvas edge

### ISSUE THREAD

**Issue by rmasoni** [Feu-Secret/Tokenmagic#139]
When an image with an animated `rotation` filter gets moved past the edge of the canvas, a row of pixels corresponding to that cut is infinitely duplicated and animates with the rest of the image.

Screen capture of the issue: https://gfycat.com/anchoredshadowyangwantibo

**Comment by Feu-Secret** [comment]
Could you put `autoFit: false` just below `padding`, and tell me if it works.

**Comment by rmasoni** [comment]
That fixed it! Thanks a lot!

Feel free to close this if it's not actually an issue.

**Comment by Feu-Secret** [comment]
> 
> 
> That fixed it! Thanks a lot!
> 
> Feel free to close this if it's not actually an issue.

Thanks for reporting the issue!
I think it is still a bug. Some filters should automatically default to `autoFit: false` to prevent artifacts.
@dev7355608, what do you think of it?

**Comment by dev7355608** [comment]
Now that I think about it: the transform filter can never be auto fit. Because what would be rendered offscreen is rotated by the filter on screen. But auto fit cut it off. So it just repeats the edge pixels.

I completely missed this fact when I was working on the filter matrix code.
