### ISSUE TITLE
Importing settings produces error

### ISSUE THREAD

**Issue by siliconsaint** [Feu-Secret/Tokenmagic#142]
Using the recommended export produces a json.  Attempting to then import those settings produces an the following error and does not update the templates within TMFX.

<img width="608" alt="Screen Shot 2021-06-24 at 9 21 48 AM" src="https://user-images.githubusercontent.com/56798973/123270570-065c5d00-d4ce-11eb-9e99-feef9e9ff895.png">

**Comment by Feu-Secret** [comment]
Oh.. what is the FVTT and Token Magic version?

**Comment by siliconsaint** [comment]
Foundry: 0.8.7
TMFX: 0.5.2

Is it a file picker issue?  Doesn't seem to be grabbing the file when "choose file" is made from local file system.

**Comment by Feu-Secret** [comment]
Just testing it now with FVTT 0.8.7 and TMFX 0.5.2.1
It's working...
![image](https://user-images.githubusercontent.com/66535080/123272461-0bd39a80-d502-11eb-99e6-7f5fddac318a.png)

**Comment by Feu-Secret** [comment]
There is a hotfix for FVTT 0.8.7, have you tried to force update this version?

**Comment by siliconsaint** [comment]
Will do that now and report back.

**Comment by siliconsaint** [comment]
This persists.  Exporting places the file on my local mac (i'm hosted for server).  Using the file picker to select the local file doesn't seem to upload the file to be used for import.
<img width="418" alt="Screen Shot 2021-06-24 at 9 42 45 AM" src="https://user-images.githubusercontent.com/56798973/123273496-b29f4300-d4d0-11eb-8e00-f5a6ff2e937f.png">

I've just hit "choose" in this picture.  Now I hit "select file" and it give the same error.  Am I doing this wrong?

**Comment by Feu-Secret** [comment]
> I've just hit "choose" in this picture. Now I hit "select file" and it give the same error. Am I doing this wrong?

No, it's the way to do. Could I connect to your session as a GM? Can you contact me on discord?

**Comment by siliconsaint** [comment]
Sure, let me setup and contact.

**Comment by siliconsaint** [comment]
So it was me. Thanks to secretfire for helping me figure this out.  For those that make the same assumptions I did.

1. Export settings locally
2. Upload settings to server (you cannot simply choose the file locally if your server is hosted, it will not upload)
3. Select file on Server using Import.
