### ISSUE TITLE
Tokens become blurry and shrinks when applying FX

### ISSUE THREAD

**Issue by rplazevedo** [Feu-Secret/Tokenmagic#144]
Whenever I apply an effect to a token, it automatically becomes blurry and very slightly shrinks. Applying additional effects makes the token even blurrier and smaller. I and on Windows 10, and using screen resolution scaling of 125% (saw this on another older issue and though it could be relevant).
![image](https://user-images.githubusercontent.com/38075882/124806527-b319ee00-df54-11eb-99cc-b9fc1a0f3972.png)
![image](https://user-images.githubusercontent.com/38075882/124806549-bad99280-df54-11eb-8d7e-0098f7388ff9.png)
![image](https://user-images.githubusercontent.com/38075882/124806674-dd6bab80-df54-11eb-92e1-d158180bb49d.png)

**Comment by j-schoch** [comment]
I am seeing this issue as well, version 0.5.2
![unknown](https://user-images.githubusercontent.com/5287619/124852361-34cc4480-df72-11eb-8ea4-10694308f700.png)

**Comment by rplazevedo** [comment]
I think this could be connected to scaling of the monitor. When I log in on a test account on another monitor with no scaling I don't get the blur.

**Comment by Feu-Secret** [comment]
Problem identified. Will be patched in the next release.
