### ISSUE TITLE
Effects are only visible for tokens that are on the same elevation

### ISSUE THREAD

**Issue by watermelonwolverine** [Feu-Secret/Tokenmagic#146]
Tested for:
- Bevel
- Adjustment
- Outline
- Glow
- Bloom
- Distortion

**Comment by Feu-Secret** [comment]
Hello. Tested just now and working. Can you confirm that no other modules are active when testing?

**Comment by watermelonwolverine** [comment]
Disabling Levels fixed the issues, sorry for the wrong bug report.

**Comment by theripper93** [comment]
The newest levels update fixes this issue, and filters are supported on tiles as well, thanks to EBER

**Comment by Feu-Secret** [comment]
> The newest levels update fixes this issue, and filters are supported on tiles as well, thanks to EBER
Hey @theripper93! Good news!
EBER or @dev7355608 is always on the front 😄
