### ISSUE TITLE
Having trouble implementing Magic Fx to ConditionLab

### ISSUE THREAD

**Issue by panda-gm** [Feu-Secret/Tokenmagic#147]
I'm not sure it I am typing the macros incorrectly? I have only got a few of them to work with my conditions. What do I need to add to the "effect value" field for the macro to work? 
![Screenshot 2021-07-12 133123](https://user-images.githubusercontent.com/87332069/125331059-7adc2c00-e315-11eb-9b5c-9f281191f384.png)

**Comment by Feu-Secret** [comment]
Sorry, you should ask questions at the module dev for active effect. It's far from TokenMagic core software.
