### ISSUE TITLE
update for tokenmagic gui

### ISSUE THREAD

**Issue by brunocalado** [Feu-Secret/Tokenmagic#148]
It can target tokens and tiles now.

[TokenMagicGUI - Copia.txt](https://github.com/Feu-Secret/Tokenmagic/files/6870093/TokenMagicGUI.-.Copia.txt)

**Comment by brunocalado** [comment]
https://user-images.githubusercontent.com/4999783/126814348-993294a3-fd8b-40ae-a3c1-9e9f87b55e8b.mp4

**Comment by Feu-Secret** [comment]
Hey @brunocalado !! Excellent work. I''ll be busy for 3 to 4 weeks until I could return on TMFX, with a lot of things to come !

**Comment by Feu-Secret** [comment]
On it.

**Comment by Feu-Secret** [comment]
The Token Magic GUI has been integrated into the V9 TMFX update. I needed to modify the macro to accomodate some FVTT API changes.. @brunocalado Can you confirm that all is ok before I close this issue?

**Comment by brunocalado** [comment]
It works.

Thank you.

![Uploading image.png…]()
