### ISSUE TITLE
Token Configuration panel does not scroll on Chrome

### ISSUE THREAD

**Issue by QuelessQuest** [Feu-Secret/Tokenmagic#15]
When attempting to configure a Token with Dancing Lights, the window will not scroll to be able to view and save the options.

Browser: Chrome, latest version
OS: Mac OS 10.15.5

![image](https://user-images.githubusercontent.com/2728882/88398586-990eec00-cd93-11ea-8991-e06fa6b02921.png)

**Comment by Feu-Secret** [comment]
Token Magic FX doesn't expose options in token configuration... you should go to the module options panel to find them. 
I think you are not posting in the good repo.  :)

**Comment by QuelessQuest** [comment]
Yup, wrong Repo, sorry about that.
