### ISSUE TITLE
Adding using an object to pass a library fails

### ISSUE THREAD

**Issue by kandashi** [Feu-Secret/Tokenmagic#153]
Any of the add/update filter functions fails to correctly obtain a preset from a library, as `if (typeof paramsArray === "string")` returns false when checking for a preset name, and incorrectly assumes that the presetArray must be an array isntead of retrieving the library.

This should possibly be changed to `if(typeof paramsArray !== "array")` or check for both objects and strings

**Comment by Feu-Secret** [comment]
Hey Kandashi. I'm on it. Sorry for the delay 😕

**Comment by Feu-Secret** [comment]
done.
