### ISSUE TITLE
TMFX and DAE, some animations do not work

### ISSUE THREAD

**Issue by TrikyEMF** [Feu-Secret/Tokenmagic#156]
Hi, 
with TMFX and DAE there are some animations that seem not to work?
For instance:
Air-field works correctly:
![image](https://user-images.githubusercontent.com/8931258/131125353-55750827-d7c2-46e8-86b8-71a50468098a.png)
Fairy fireflies does not:
![image](https://user-images.githubusercontent.com/8931258/131125395-0e841698-0eac-4518-8539-1cd6d9bbb46a.png)

**Comment by tposney** [comment]
That's probably a DAE issue not coping with the spaces in the name.
