### ISSUE TITLE
[Question] How to trigger Wound/Splash macro automatically?

### ISSUE THREAD

**Issue by Kirin92** [Feu-Secret/Tokenmagic#160]
Hey there.
My question is: How can I trigger the Wound macro automatically if a token takes damage and if the token is healed it goes away? 
It would be really helpful.
Thanks~

**Comment by itamarcu** [comment]
I made one for myself, I'll share it here (maybe it could be added to this module).

https://pipe.miroware.io/60781d17a333fb12a3acb21e/maybe%20permanent/automatic_wounds.webp

The code creates a wound with size based on damage, and reduces wound sizes based on healing amount.

source code:  https://github.com/itamarcu/shemetz-macros/blob/master/scripts/tokens/automatic-wound-effects.js

(just need to call the register function)
