### ISSUE TITLE
Error with templates. 

### ISSUE THREAD

**Issue by Fridan99** [Feu-Secret/Tokenmagic#163]
I have a slight problem with the templates. When I place a template (by spell or otherwise), it happens that I cannot delete it afterwards..... f12 console error.... is only deleted when I refresh f5. Also, when I try to delete it, the screen is totally blocked and the menu on the left, I can not change and is locked in the templates option.
![1](https://user-images.githubusercontent.com/86131373/145718860-63450036-44fd-4a3c-a642-992936d43993.jpg)

Foundry 0.8.9
Dnd5e 1.5.5
Token Magic FX 0.5.2.1

I have discovered which module creates the conflict. 

DF Quality of Life          and      Token Magic FX

**It seems that by deactivating the DF Quality of Life, the problem is eliminated, so I understand that the problem must be of the DF Quality of Life itself.**

https://github.com/flamewave000/dragonflagon-fvtt/issues/238

**Comment by Feu-Secret** [comment]
Corrected with the last release.
