### ISSUE TITLE
Most functions broken in v9

### ISSUE THREAD

**Issue by GambetTV** [Feu-Secret/Tokenmagic#164]
Shadows and most other filters you can place on objects no longer work. About the only one I can get to work is the Outline, and that only works for the current map. If you refresh or change maps, the outline will vanish 90% of the time.

**Comment by Feu-Secret** [comment]
Update for FVTT V9 is in progress. Scheduled for the 12/21 or 12/22.

**Comment by Feu-Secret** [comment]
Done.
