### ISSUE TITLE
[V9] Locked FPS when enabled

### ISSUE THREAD

**Issue by megahead11** [Feu-Secret/Tokenmagic#169]
Running on v9; 

I'm running at maximum setting uncapped FPS (so it usually runs at 144 FPS). With this module enabled, the FPS tanks all the way down to 50-60 fps. The difference is notable even with FPS capped.

I'm not certain if this is a limitation with tokenmagicfx for maintaining the animation speed that is hidden or something.

**Comment by Feu-Secret** [comment]
done.
