### ISSUE TITLE
[Enhancement] Add thumbnail images to all compendium macros

### ISSUE THREAD

**Issue by itamarcu** [Feu-Secret/Tokenmagic#170]
Currently, all the macros have no thumbnail image at all, and I think it would be nice to add images!

Here's how I did it on my own server, for example (with some of my favorite effects):

![image](https://user-images.githubusercontent.com/6516621/147830656-868833fb-b0ab-4069-b8dd-ba8fe3fa5090.png)

Higher res example:

![image](https://user-images.githubusercontent.com/6516621/147830739-871496bd-d25a-4321-ae2c-56d1696b8662.png)

Some minor choices to be made if you agree:
- Should the images be local files downloaded along with the macro, or should they be imgur links?
- Which token should be the "face" of all these effects?  (in the example above it's one of my PCs who uses the default goblin warrior image)
- Should there be a background (e.g. white/gray/black) or should they be PNGs with a transparent background?
- What should the "clear effects" symbol be?

I would be happy to help create these images myself for the module, with a pull request, if others agree with this suggestion.

**Comment by Feu-Secret** [comment]
Hey @itamarcu  , thank you for your proposal. It would be great!

- The image should be local files. Also, very important, the image should be royalty free.
- A background color is required. Black is a good choice.
- For the "clear effects", broom is a good idea!

**Comment by itamarcu** [comment]
@Feu-Secret I made some sample images, and got a quick process to create more of them.

![image](https://user-images.githubusercontent.com/6516621/149936935-69814a03-193e-4be2-8965-1666763d1761.png)


- Source image is [from here](https://opengameart.org/content/js-actor-witch), under Creative Commons license
- I chose a purple background instead of a black background, so that some effects like Drop Shadow are visible
- I'll create them at a final size of 128x128, `.webp`, about 20 KB each for a total of about 0.2MB
- I temporarily altered some of them (like Bevel and Outline) to have a higher thickness for a more noticeable effect in the thumbnail

What do you think?

**Comment by Feu-Secret** [comment]
Very nice!!

**Comment by itamarcu** [comment]
![image](https://user-images.githubusercontent.com/6516621/150373879-e467eabb-a6ab-446f-8dba-753376c00bf7.png)

**Comment by Feu-Secret** [comment]
Added ! Many thanks for your contribution.
