### ISSUE TITLE
getControlledPlaceables() does not work in PF2e, causing macros to fail

### ISSUE THREAD

**Issue by itamarcu** [Feu-Secret/Tokenmagic#178]
(PF2e v3.3.0, TokenMagic FX v0.5.3)

None of the macros work for me, because they all rely on the `getControlledPlaceables` function which has the following line:

```js
    switch (canvas.activeLayer.name) {
        case TokenLayer.name:
```

When debugging, I see that:
`canvas.activeLayer.name` = `'TokenLayerPF2e'`
`TokenLayer.name` = `'TokenLayer'`

and for that reason, the code enters none of the cases, ending up with a list of 0 controlled placeables, causing nothing to happen.

**Comment by itamarcu** [comment]
I believe a solution might be to change the case to `case canvas.tokens.name`.

For now, as a workaround, I can type the following in the console to temporarily fix the issue:
```js
Object.defineProperty(canvas.tokens, "name", {
    get: function() { return 'TokenLayer' }
});
```

**Comment by Feu-Secret** [comment]
@itamarcu Thank you for the report!

**Comment by rsimoes** [comment]
It'd be better to just not check for exact constructor names

**Comment by rsimoes** [comment]
![Screenshot from 2022-01-30 16-05-10](https://user-images.githubusercontent.com/161220/151719802-6615336f-ef7a-44dd-851b-0545e67d128c.png)
