### ISSUE TITLE
Potential Conflict: ASE Template Border Override disabled due to conflict with TokenMagixFX module

### ISSUE THREAD

**Issue by Fridan99** [Feu-Secret/Tokenmagic#179]
I don't know if this is a bug or not....
I just got this warning in Foundry and the console. 
Something about **ASE Template Border Override disabled due to conflict with TokenMagixFX module**

Foundry 9.245
Dnd5e 1.5.7
TokenMagicFX 0.5.3

![9](https://user-images.githubusercontent.com/86131373/151801813-d5127cac-14d1-4f48-bd93-cc7b6c0d7548.jpg)

![10](https://user-images.githubusercontent.com/86131373/151801826-e9007411-422c-43ba-b32f-df1ee7d3945c.jpg)

**Comment by azarius74** [comment]
Any word on this bug?

**Comment by Feu-Secret** [comment]
The error thrown in your screenshot seems to not be related to TMFX.
The libWrapper message about disabling ASE override is due to the fact that our two modules are "patching" the same foundry code. Then, libWrapper disables an override according to the priority from libWrapper options.
