### ISSUE TITLE
Effects aren't persistent on tokens. 

### ISSUE THREAD

**Issue by jsimmonsathome** [Feu-Secret/Tokenmagic#180]
Imported module. Added macros to bar from Compendium. Work great, until I click somewhere else, then any applied macro effects disappear from the token. They remain persistent in the game, as far as the macro is concerned, because I can't reapply them. I have to use the "clear all" macro, then I can apply it again.

PCs report if I click on an NPC the effect just flickers for them, then is gone instantly. If I apply it to their token, it remains until they click off as well, then it's gone. 

Happens to GM and Players.

Foundry Version: 9.245
Lancer 1.1.0

Modules installed:
Cautious Gamermaster's Pack
Drag Ruler
Drag Upload
Fog Manager
Grape Juice Isometrics
Hex Token Size Support
Lancer Clocks
libWrapper
Shared Vision
socketlib
Token Action HUD
Token Magic FX

**Comment by itamarcu** [comment]
I'm having a similar issue, possibly not the same. After applying an effect on a newly dragged-in token, the effect works fine for me;  however, after I refresh the effect is gone and I am unable to add new effects.  When I try adding new effects I get a console error: 

```js
foundry.js:316 TypeError: Cannot read properties of null (reading 'scale')
[Detected 1 package: tokenmagic]
    at r.get (display.min.js:8:8903)
    at r.get (sprite.min.js:8:4676)
    at FilterSplash.PIXI.Filter.calculatePadding (FilterProto.js:56:33)
    at FilterSplash.get [as padding] (FilterProto.js:22:26)
    at _fxPseudoEqual (tokenmagic.js:771:45)
    at tokenmagic.js:857:30
(...)
```

and like the above post, it only gets fixed when using the Delete Filters macro.

**Comment by jsimmonsathome** [comment]
Conflict with Grape Juice Isometrics. When I enable that one, this starts happening. Pinging that creator. Thanks!
