### ISSUE TITLE
Feature Suggestion: addFiltersOnTargeted

### ISSUE THREAD

**Issue by Dumbhuman** [Feu-Secret/Tokenmagic#2]
Having the ability to apply filters to targeted tokens could, combined with other modules and a little macro magic, open up all sorts of possibilities for automatically applying spell effects from templates such as turning someone to stone, highlighting them with Faerie Fire, actually setting them on fire, making them fly/levitate, etc.

![tokenmagic](https://user-images.githubusercontent.com/63615591/86401153-9e7a8a00-bc5e-11ea-98b0-e393266fd7ed.gif)

**Comment by Feu-Secret** [comment]
I'm on it ! Will be in the 0.1.1 to come (a few days).

**Comment by Feu-Secret** [comment]
Added in v0.1.1-alpha release.
