### ISSUE TITLE
Token Magic Fx not working on version v.10

### ISSUE THREAD

**Issue by danil0man** [Feu-Secret/Tokenmagic#203]
Hello Feu. I wonder if you could update Token Magic FX to work with version v.10 as currently is not working. All effects don't apply anymore to the tokens.

**Comment by Kuresov** [comment]
The specific exception is `TypeError: Error thrown in hooked function '' for hook 'canvasReady'. canvas.background is undefined` from https://github.com/Feu-Secret/Tokenmagic/blob/e21960848ea9bfaff52077fe1846cd0c14482189/tokenmagic/module/tokenmagic.js#L1557

Looks like it doesn't exist anymore according to the API docs. I'm reviewing them to see if I can figure out what the equivalent is.

**Comment by sanguaire** [comment]
Maybe the equivalent is

`const bgtiles = canvas.tiles.placeables.filter(t => !t.document.overhead)`

**Comment by sanguaire** [comment]
I made a dirty fix with this changes (see attached files).
[files.zip](https://github.com/Feu-Secret/Tokenmagic/files/9469856/files.zip)

**Comment by OsiJr** [comment]
The PR is ready for review. Quite a few corners were cut and might be worth a tidy up in future to remove some of the <=0.8 support to improve the code quality for future maintenance (happy to help with that adhoc).

**Comment by bradleyquinn** [comment]
Thank you guys for jumping on fixing this.  My campaign is kinda a mess without it.  Looking forward to seeing that merge!

**Comment by Feu-Secret** [comment]
I'm working on it as well as all others waiting PR. A release should be available in a couple hours.

**Comment by atkinsgt** [comment]
> I'm working on it as well as all others waiting PR. A release should be available in a couple hours.

Super excited to see this. For something that primarily sits in the background for me, I'm eagerly awaiting your work! Thank you for jumping on this.

**Comment by Feu-Secret** [comment]
Done!
