### ISSUE TITLE
Foundry V10 measured templates not displaying FX correctly in most recent update.

### ISSUE THREAD

**Issue by Thronan** [Feu-Secret/Tokenmagic#209]
Hello, when ever I apply a FX to a measured template it seems to only apply to the edge of the template, and I also am no longer seeing the squares highlight with the player colour. I did check the log and noticed there was an error entry upon drawing the template.

I have tried it with just TMFX active and the problem remains.

![token magic fx bug](https://user-images.githubusercontent.com/113313249/189550305-fad196ae-d24d-46e3-bd53-d6e2f661ea1d.PNG)

![token magic fx log](https://user-images.githubusercontent.com/113313249/189550396-067d5a06-74a8-4df9-b323-7e329d8336c3.PNG)

**Comment by Feu-Secret** [comment]
Investigating.

**Comment by Feu-Secret** [comment]
Issue identified. A fix will be available in the next 24/48h.

**Comment by OsiJr** [comment]
Is this where the texture isn't being auto-set to the black-opaque texture?

**Comment by Feu-Secret** [comment]
> Is this where the texture isn't being auto-set to the black-opaque texture?

Yes, that's it.
