### ISSUE TITLE
Unable to automatically apply custom textures

### ISSUE THREAD

**Issue by debraun1** [Feu-Secret/Tokenmagic#212]
Hello, 

Thanks for updating the module for v10. I encountered an issue. I can't seem to make 'ovverrides' automatically recognise custom textures. The settings should be correct and used to work before v10. As shown in the pictures attached, it seems like the module is not automatically applying the texture. The selected image works correctly if added as texture to the template after it has been placed. I attach an error that appears in the console when I try to apply place the template in case it's relevant.

![image](https://user-images.githubusercontent.com/113129805/190008497-7450f52e-5bc3-4423-8c0e-1ae6a71dd4fd.png)
![image](https://user-images.githubusercontent.com/113129805/190008692-74165dd3-2443-4bd3-8da7-efa43eb3ed54.png)
![image](https://user-images.githubusercontent.com/113129805/190009550-e2fa5b16-d255-48e8-aadf-f185ca627ff6.png)
![image](https://user-images.githubusercontent.com/113129805/190011636-ffc0b18a-dca0-4182-899e-bc0badea3a61.png)

**Comment by Feu-Secret** [comment]
Under investigation.
