### ISSUE TITLE
`loop` flag for Sprite filter is not working

### ISSUE THREAD

**Issue by LeRatierBretonnien** [Feu-Secret/Tokenmagic#227]
**Module Version:** v0.6.1.2
Foundry v10.288

When applying "sprite" filter with a webm, the video is playing infinitly, even if 'loop' is set to false : 

![image](https://user-images.githubusercontent.com/1085008/197349570-f77bea75-72dd-4f94-863a-c2b9114e165e.png)

**Comment by sladecraven** [comment]
And I think the issue is here : 
![image](https://user-images.githubusercontent.com/1085008/197349738-bcb8cd5d-d2ba-468f-8200-55db74fceb0d.png)

Should be `this._playVideo(this._loop);` (I think)

**Comment by sladecraven** [comment]
The proper fix is : 

```
        if ( value ) game.video.play(source, {playing: true, loop: this._loop});

```
