### ISSUE TITLE
[BUG] no automatic template effects option in the settings for token magic fx

### ISSUE THREAD

**Issue by xavien12** [Feu-Secret/Tokenmagic#230]
**Module Version:** 0.6.1.2

**Describe the bug**
There is no automatic template effects option in the settings for token magic fx.

**To Reproduce**
1. Go to 'configure game setting'
2. Scroll down to 'token magic fx'
4. See that there is no automatic template effects option.

**Expected behavior**
The automatic template effects option appears when going to configure game setting and choosing the token magic fx.

**Screenshots**
![automatic template](https://user-images.githubusercontent.com/58941502/200162215-ece25218-8314-4cd8-ad21-19761a46248b.png)

**Browser:**
Firefox

**Foundry Version:** 
v10.288

**Game System:** 
PF2e

**Additional context**
I turned off all the other modules and the error still persists.

**Comment by javijuji** [comment]
Running into the same issue. Did you ever figure this out @xavien12 ?

**Comment by Aedif** [comment]
PF2e support has been added in release v0.6.3
