### ISSUE TITLE
[BUG] Unable to download module in v11 Stable

### ISSUE THREAD

**Issue by DiceAndEasy** [Feu-Secret/Tokenmagic#246]
**Module Version:** v5.2.1

**Description**
When trying to download and install the module through Foundry VTT v11 Stable version, I get the following error:
![image](https://github.com/Feu-Secret/Tokenmagic/assets/86520580/e7c22575-d134-4117-bae4-90358d3d41d2)

**Repro Steps**
1. Launch Foundry VTT v11.299
2. Go to "Add-On Module" tab
3. Click "Install Module"
4. Type "Tokenmagic" in the search
5. Click "Install" on "Token Magic FX"
6. See the error message

**Expected behavior**
Being able to download and install the module through Foundry.

**Screenshots**
![image](https://github.com/Feu-Secret/Tokenmagic/assets/86520580/e7c22575-d134-4117-bae4-90358d3d41d2)

**Browser:**
Local Foundry instance.

**Foundry Version:** 
11.1299

**Game System:** 
N/A

**Additional context**
N/A

**Comment by vlamirsanto** [comment]
Same problem here.

**Comment by joebags99** [comment]
Same for me as well.

**Comment by EvldoaTV** [comment]
And for me also

**Comment by Kaallis** [comment]
Same here

**Comment by Aedif** [comment]
v11 support has been added: https://github.com/Feu-Secret/Tokenmagic/releases/tag/v0.6.4
report if you find any issues

**Comment by Kaallis** [comment]
![Snag_55b2677](https://github.com/Feu-Secret/Tokenmagic/assets/25804511/10a0c375-67e8-4512-a333-4c173f915443)

**Comment by Aedif** [comment]
Secret need to update foundry DB with the latest v11 and v10 releases. Once that's done updating should work again.

In the meantime you can re-install the module by pasting the link it directly in the manifest link:
 https://raw.githubusercontent.com/Feu-Secret/Tokenmagic/master/tokenmagic/module.json

**Comment by rmasoni** [comment]
It says the last verified Foundry version is 0.8.9.

<img width="400" alt="image" src="https://github.com/Feu-Secret/Tokenmagic/assets/62244/5be46469-a289-436b-bb91-2ff9c24e45c2">

**Comment by Feu-Secret** [comment]
Fixed!
