### ISSUE TITLE
zip file should not be committed to repository

### ISSUE THREAD

**Issue by pdf** [Feu-Secret/Tokenmagic#26]
Committing binaries to the git repo is poor form - binaries cannot be stored or diff'd efficiently, so the repository size grows dramatically over time.

Consider instead using the releases feature on Github to attach the zip to a tag.

**Comment by Feu-Secret** [comment]
You're right. The zip will be published with a release and the module.json download link will point to it.

**Comment by Feu-Secret** [comment]
done !
