### ISSUE TITLE
[BUG] Incompatible with Foundry V12

### ISSUE THREAD

**Issue by Cerzix** [Feu-Secret/Tokenmagic#268]
**Module Version:** v0.6.7

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**
You cannot place spell templates anymore.

**To Reproduce**
1. Create an actor
2. Assign a spell with a template
3. Cast it and try to place template

**Expected behavior**
To be able to place Spell Templates

**Screenshots**

**Browser:**
 - 

**Foundry Version:** V12

**Game System:** System: DnD 5e 3.2.0

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by VirusNik21** [comment]
This works if you use the "Override" setting.
For example, if I put a specific spell - Fireball - and then place a template of this spell - everything works.

When auto-defining the module lost the names of the template types and instead specifies them as [object Object].

**Comment by r0nnoC** [comment]
Still experiencing this issue. Tried the override setting but still am receiving the same error when attempting to place the template.

Also tried reloading the module and reimporting and recreating the spell.

Seems others are experiencing this issue as well: https://www.reddit.com/r/FoundryVTT/comments/1dd47xv/5e_failed_to_place_measured_template/

**Comment by Rughalt** [comment]
I am pretty sure I have fixed version somewhere, so I will make an update to the module!

**Comment by Rughalt** [comment]
Even better, if you could make a PR I will merge it today

**Comment by r0nnoC** [comment]
You guys are the goat https://github.com/Feu-Secret/Tokenmagic/pull/269

**Comment by cezaro40** [comment]
Hi, has this gone in? Were should we expect an update? or is there something that i could do to circumvent the issue in my current games?

**Comment by ddbrown30** [comment]
Judging from the latest release, it looks like you've added v12 support but you didn't update the module.json file and you haven't pushed a release in the packages tool.

**Comment by Armandeus66** [comment]
Effects applied by macros using this module don't take effect until after a browser refresh.
This module also seems to interfere or disable animations applied by Automated Animatons and Sequencer too.
The change log mentions a D&D update last week. **Please consider a PF2E and Foundry v12 update soon.**
**Thanks for making this module!** It's great, and I am a heavy user. I especially love the token drop shadow effect macros!
System PF2E, Foundry v12

**Comment by Rughalt** [comment]
Please remember that while I can make patches I am just a contributor - I do not have release privileges on Foundry side. I am not the module maintainer too - so if you have PRs I will gladly accept them and merge them into the package.

**Comment by khionu** [comment]
I would be keen on seeing V12 compatibility wrapped up, enough where I'd like to put a $150 bounty it working. I'll also pay $25 to the owner or whoever has perms on a V12 release.

**Comment by alessiocali** [comment]
I can confirm [v0.6.8](https://github.com/Feu-Secret/Tokenmagic/releases/tag/0.6.8) works on V12, you can send the bounty to @IsendurHun I guess :D (see commit https://github.com/Feu-Secret/Tokenmagic/commit/1c86b70ca80e93899c9046de7f8f96e1c955669a)

That said  the owner said they are no longer maintaining the module, as they are now part of the Foundry staff, and [are looking for maintainers](https://github.com/Feu-Secret/Tokenmagic/issues/195), so until someone takes the mantle (or any future Foundry release merges this plugin) the only option is download and install 0.6.8 manually

**Comment by khionu** [comment]
@IsendurHun if you're wanting to accept the bounty, could you reach out to me on Discord (khionu) or email (see GH profile)? Can coordinate privately.

Thank you very much!

**Comment by Tapircurr** [comment]
> I can confirm [v0.6.8](https://github.com/Feu-Secret/Tokenmagic/releases/tag/0.6.8) works on V12, you can send the bounty to @IsendurHun I guess :D (see commit [1c86b70](https://github.com/Feu-Secret/Tokenmagic/commit/1c86b70ca80e93899c9046de7f8f96e1c955669a))
> 
> That said the owner said they are no longer maintaining the module, as they are now part of the Foundry staff, and [are looking for maintainers](https://github.com/Feu-Secret/Tokenmagic/issues/195), so until someone takes the mantle (or any future Foundry release merges this plugin) the only option is download and install 0.6.8 manually

How would one go about installing it manually? I tried just downloading and extracting the tokenmagic.zip into the folder in foundry but the bug where it can't see the damage type is still there.
![token magic bugs](https://github.com/user-attachments/assets/399265b0-1e0d-476a-86ae-53bee5aa10f6)

**Comment by alessiocali** [comment]
Ah that, I think it's still there, when I said it worked I referred to the bug where it couldn't place the template in any way. On a wild guess, [object Object] is likely a minor issue to fix, maybe I'll give it a shot on some spare time.

**Comment by alessiocali** [comment]
I don't have it on a locally built version so likely this has been fixed by https://github.com/Feu-Secret/Tokenmagic/issues/270 and it just needs a new release - @Rughalt could you author one ? I would suggest also `npm audit fix` since there seems to be a vulnerability pending.

@Tapircurr  Until then, if you want to get down and dirty with `node`

```
git clone https://github.com/Feu-Secret/Tokenmagic.git
cd Tokenmagic
npm install 
npm run build
```

Then copy everything from the `tokenmagic` (lowercase) folder where you installed the foundry module (delete old contents from the previous installation first).

**Comment by IsendurHun** [comment]
> Ah that, I think it's still there, when I said it worked I referred to the bug where it couldn't place the template in any way. On a wild guess, [object Object] is likely a minor issue to fix, maybe I'll give it a shot on some spare time.

@Aedif already fixed this it, just need new version as you mentioned it

**Comment by Rughalt** [comment]
So I have talked with @Feu-Secret and will be taking over the repo and the Foundry package listing and will release updated version as soon as I get both access!

**Comment by zero127** [comment]
This is the last piece holding me up from V12. Really grateful you're taking the mantle!

**Comment by Rughalt** [comment]
Hi! I released new version, if there are any other issues please report them in the new issue so its easier for me to manage!
