### ISSUE TITLE
[BUG] Token Magic FX is not working and not showing in config setting

### ISSUE THREAD

**Issue by TheXeno30** [Feu-Secret/Tokenmagic#274]
**Module Version:** v0.6.9.

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

no console error

**Describe the bug**
have several filters on token and now no token has any filters and token magic FX not showing in the config settings. Worked yesterday.

**To Reproduce**

**Expected behavior**
be able to apply effects. tokens in picture should be rotating slitely and have drop shadows

**Screenshots**
![image](https://github.com/user-attachments/assets/f2c0858d-8b05-4566-80e9-6f11f6ce703a)

**Browser:**
chrome

**Foundry Version:** 
12.331

**Game System:** 
DND 3.3.1

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by TheXeno30** [comment]
![image](https://github.com/user-attachments/assets/3127abce-ce54-477a-b060-064c77f489fc)
![image](https://github.com/user-attachments/assets/e3b4e72f-048e-4c16-9473-ba4348184891)

**Comment by TheXeno30** [comment]
after restart of server it make this console error 
![image](https://github.com/user-attachments/assets/decef962-241a-418d-9e58-3285e0dbd84d)

**Comment by roi007leaf** [comment]
Yup can confirm happens to me too, module is not usable at all currently

**Comment by Rughalt** [comment]
Did it happen after updating something? If yes it may have been change in D&D5 system that broke things; I will try to fix it.

**Comment by sonofkyusss** [comment]
Hi,
It seems to be the last version of Sequencer (3.3.5) that "breaks" TMFX.
I've downgraded to 3.3.4 and TMFX works again.
