### ISSUE TITLE
Auto templates do not appear in Forge hosted games

### ISSUE THREAD

**Issue by Sparkasaurusmex** [Feu-Secret/Tokenmagic#32]
Although token FX work, auto templates do not appear.

**Comment by Feu-Secret** [comment]
After an on-site intervention, it appears that a path to a dnd5e file can't be resolved. Foundry is hosted on Forge. Here the screen copy :
![bug auto template](https://user-images.githubusercontent.com/66535080/91226689-ab2ed200-e725-11ea-8bd0-6c5232715c02.jpg)

**Comment by Feu-Secret** [comment]
On Forge, modules are put into the "bazaar". It is possible to prevent Forge from doing this with :
https://raw.githubusercontent.com/Feu-Secret/Tokenmagic/master/tokenmagic/module.json?bazaar=disabled

**Comment by Feu-Secret** [comment]
I'm closing this issue. TMFX now works in the Forge. @Sparkasaurusmex , thank for the report!
