### ISSUE TITLE
Enhancement: Rotate Effect

### ISSUE THREAD

**Issue by Dumbhuman** [Feu-Secret/Tokenmagic#35]
I know that there's a mechanical rotation tied to tokens in game, but I would love the ability to just rotate the image of a token without changing its functional rotation.  This could be used to quickly fix tokens not set up to face south (Foundry's default assumption) as well as to animate rotation for spell templates on things like Fog Cloud, Whirlwind, Dust Devil, etc. (my primary goal).

**Comment by Feu-Secret** [comment]
Sprites transformation is a functionality in the pipeline (translation, rotation, shrinking, enlarging). I cannot give a deadline yet. In the meantime, to simulate a rotation, you can use a twist filter with a very large radius (not very efficient, but works).

**Comment by Dumbhuman** [comment]
Yeah, I figured out that trick with the Twist filter a while ago, but I'm not sure if it's possible to animate that to get a consistent clockwise spin.  It can work as a quick fix to the default orientation scenario though.

Anyway, I'm glad to hear that you're already planning for other transformation features as well.  My little flying effect currently uses the Bulge filter with a large radius to enlarge/shrink as well as the Twist Filter with a large radius to get some oscillating rotation so it sounds like it will get a nice performance boost in the future.

**Comment by Feu-Secret** [comment]
> Yeah, I figured out that trick with the Twist filter a while ago, but I'm not sure if it's possible to animate that to get a consistent clockwise spin. It can work as a quick fix to the default orientation scenario though.

Not with a twist filter, distortion is inevitable.

> Anyway, I'm glad to hear that you're already planning for other transformation features as well. My little flying effect currently uses the Bulge filter with a large radius to enlarge/shrink as well as the Twist Filter with a large radius to get some oscillating rotation so it sounds like it will get a nice performance boost in the future.

It's pulling out the chainsaw when you just need a butter knife. I know 😄

**Comment by Feu-Secret** [comment]
done !

**Comment by Dumbhuman** [comment]
Working very well for me!

One tiny detail, but "clockWise: false" seems to be required to get an actual clockwise rotation while "clockWise: true" appears to produce counter-clockwise rotation.

**Comment by Feu-Secret** [comment]
> One tiny detail, but "clockWise: false" seems to be required to get an actual clockwise rotation while "clockWise: true" appears to produce counter-clockwise rotation.

oops... i will fix it for the next release.

**Comment by Feu-Secret** [comment]
done.
