### ISSUE TITLE
Enhancement: Masking Interiors of Fields/Auras/Templates

### ISSUE THREAD

**Issue by Dumbhuman** [Feu-Secret/Tokenmagic#36]
Essentially the idea here would be to allow for fields/auras/templates to apply their effects as a ring/border of adjustable thickness rather than always filling their entire area.  This could be useful for various wall spells that encircle an area, for example, or in situations where you want the FX to highlight an area of effect without obscuring more of that map than is necessary.

**Comment by Feu-Secret** [comment]
I like the idea! I'll see what I can do.

**Comment by Feu-Secret** [comment]
Scheduled for the next milestone... a little preview:
![image](https://user-images.githubusercontent.com/66535080/91650734-7c955c00-ea83-11ea-8b3e-039593ef1f2e.png)

**Comment by Dumbhuman** [comment]
Very nice!  That will open up a lot of extra possibilities.

**Comment by Feu-Secret** [comment]
done.
