### ISSUE TITLE
Bug: MeasuredTemplate#update() throws exception when adding texture

### ISSUE THREAD

**Issue by sPOiDar** [Feu-Secret/Tokenmagic#39]
I've not been able to track this down yet. When Tokenmagic is enabled, adding a texture to a template from the MeasuredTemplateConfig menu throws the following exception the first time a particular texture image is loaded, upon saving the template:

```
Graphics.js:850 Uncaught (in promise) TypeError: Cannot read property 'clear' of null
    at r.clear (Graphics.js:850)
    at MeasuredTemplate.refresh (foundry.js:37191)
    at MeasuredTemplate._onUpdate (foundry.js:37414)
    at Scene._onUpdateEmbeddedEntity (foundry.js:29792)
    at Function._handleUpdateEmbeddedEntity (foundry.js:10735)
    at Function._handleUpdateEmbeddedEntity (foundry.js:29840)
    at Scene.updateEmbeddedEntity (foundry.js:10704)
    at async MeasuredTemplate.update (foundry.js:12469)
    at async MeasuredTemplate.update (PlaceableObjectProto.js:140)
    at async MeasuredTemplate.PlaceableObject._TMFXunsetFlag (PlaceableObjectProto.js:35)
```

The following are the observed conditions from testing, starting from a fresh load of the page:

1. Existing textured templates do not throw an exception on page load :heavy_check_mark: 
2. Adding a new image texture to a newly created template throws the excetion :heavy_multiplication_x: 
3. Changing the texture on the template from test (2) to a different image does not throw the exception :heavy_check_mark: 
4. Creating a new template and setting the texture to the image used in the template from test (2) does not throw the exception :heavy_check_mark: 
5. Creating a new template and setting the texture to an image that has not previously been used throws the exception :heavy_multiplication_x: 

So, there's some caching going on, and I suspect some sort of order-of-operations problem.

**Comment by Feu-Secret** [comment]
I think I know what's happening. When there is a texture change, foundry performs a full redraw (which is asynchronous!), the full redraw clear all pixi containers (for the MeasuredTemplate, this.template is null the time to load the image and rebuild the containers). Since a full redraw is asynchronous, when update hooks are called, the containers may not be ready.

If, in a very tight time period, an update hook cause a refresh of the template while a texture is loading... BOOM !

Thus, this bug is also dependent on the power of the computer and the type of storage (ssd, etc.), the faster the texture loads, the more the chances of seeing the bug appearing decrease (if the texture is cached, the operation is very fast). It is also dependant of the asynchronous load at the time of the full redraw.

**Comment by Feu-Secret** [comment]
To reproduce the bug on my computer, I had to decrease the timeout in the preUpdateMeasuredTemplate.

```
Uncaught (in promise) TypeError: Cannot read property 'clear' of null
    at r.clear (Graphics.js:850)
    at MeasuredTemplate.refresh (foundry.js:36794)
    at MeasuredTemplate.<anonymous> (DefaultTemplateOnHover.js:35)
    at MeasuredTemplate._onUpdate (foundry.js:37017)
    at Scene._onUpdateEmbeddedEntity (foundry.js:29378)
    at Function._handleUpdateEmbeddedEntity (foundry.js:10319)
    at Function._handleUpdateEmbeddedEntity (foundry.js:29426)
    at Scene.updateEmbeddedEntity (foundry.js:10288)
    at async MeasuredTemplate.update (foundry.js:12053)
    at async MeasuredTemplate.update (PlaceableObjectProto.js:157)
```

**Comment by Feu-Secret** [comment]
Also, this bug could appear in foundry without question of token magic or not. If a refresh takes place while the full redraw operation is not completed. (it could happen in rare concurrent situations)

**Comment by sPOiDar** [comment]
Hrm interesting, I could produce it consistently, but only with TMFX loaded, though I was testing on a machine 200-300ms away (US from AU), so if latency or transfer time is an issue, that could contribute.

**Comment by Feu-Secret** [comment]
Atropos opened an issue in gitlab
https://gitlab.com/foundrynet/foundryvtt/-/issues/3314
But it's closed now.

**Comment by sPOiDar** [comment]
Ah, I suspect that means he fixed it in the 0.7.x series, I'll do some digging to confirm.

**Comment by sPOiDar** [comment]
BTW, not directly related to this issue, but I noticed this:
https://github.com/Feu-Secret/Tokenmagic/blob/5271b09a0cdbc50cd2b9377eb5752d86fc762d72/tokenmagic/module/proto/PlaceableObjectProto.js#L140
should `return` the result, as the patched function does - I've not confirmed that the return value is used anywhere, but if it does get used, this will break something.

**Comment by Feu-Secret** [comment]
> should `return` the result, as the patched function does - I've not confirmed that the return value is used anywhere, but if it does get

Oops ! I should be reviewed... 😏

**Comment by Feu-Secret** [comment]
Concerning the issue, monkeypatching refresh is fixing it. If the template is destroyed, the refresh is useless.

```js
MeasuredTemplate.prototype.refresh = (function () {
    const cachedMTR = MeasuredTemplate.prototype.refresh;
    return function () {
        if (this.template && !this.template._destroyed) {
            return cachedMTR.apply(this);
        }
        return this
    };
})();
```

**Comment by Feu-Secret** [comment]
done.
