### ISSUE TITLE
Creating a drop down menu through Macros

### ISSUE THREAD

**Issue by Iankid** [Feu-Secret/Tokenmagic#40]
I want to make a drop down menu for selecting effects to apply, but my coding skill is limited.
I have a macro that creates a drop down menu for vision selection, and have edited that to my specific vision needs. But that's close to the limit of what I can do.

My intention is to create a drop down list that when selected and applied, adds the listed FX to the token. (Conditions are what I have in mind). Bonus if the drop down can also toggle off said effect.

**Comment by Feu-Secret** [comment]
Hi Iankid.
Regarding the creation of macros and the need for help, I strongly advise you to go to the foundry discord and explain your need in the "macro-polo" channel. A caring community (and macro experts) could help you with this task, better than me ! 😃 
https://discordapp.com/invite/DDBZUDf
