### ISSUE TITLE
Bug: Template Texture Tessellation 

### ISSUE THREAD

**Issue by bibicvc** [Feu-Secret/Tokenmagic#43]
TokenMagic tessellates textures as of the most recent update. The intended behavior is to resize textures to the size of the template. Attached is a picture with the mod off:
 
![image](https://user-images.githubusercontent.com/68487801/92299176-6de8f200-ef26-11ea-950e-ad37a0c2b40e.png)

And with the mod on: 

![image](https://user-images.githubusercontent.com/68487801/92299232-f10a4800-ef26-11ea-8445-1bb434127501.png)

These are my current mod settings: 
![image](https://user-images.githubusercontent.com/68487801/92299242-ff586400-ef26-11ea-9d1a-488410b1e861.png)

Let me know if any other information would be useful

**Comment by Feu-Secret** [comment]
Thank for the report. I'm investigating.

**Comment by Feu-Secret** [comment]
It's the normal foundry behavior. By default, foundry tile the texture. Centered texture is the action of another module. Comes in my mind Mess Moerills Enhancing Super Suit(e). The compatibility of our two modules may have been broken with the latest release. I will see what I can do.

**Comment by bibicvc** [comment]
I see - I'm also using mess so that makes sense.

**Comment by Feu-Secret** [comment]
Fixed in the v0.4.2b-alpha
