### ISSUE TITLE
Transform Filter causes Token to disappear (macOs)

### ISSUE THREAD

**Issue by QuelessQuest** [Feu-Secret/Tokenmagic#45]
Execution of a transform file causes the token to disappear. It returns when the effect is canceled. For the duration, the token just vanishes and there is no animation or anything.

macOS Catalina

**Comment by Feu-Secret** [comment]
Hi @QuelessQuest. 
Is the token disappearing with the bundled macros ? Check your TM compendium and launch macro 33-T01, 33-T02, 33-TO3 and 33-T04, and tell me what's happening.
What is your foundry version ? Have you disabled all other modules ?
Could you send me the specification of you GPU (brand, memory, or better, a link to all specs) ?

**Comment by Feu-Secret** [comment]
I also need a screenshot of Token Magic FX option panel. Thank.

**Comment by QuelessQuest** [comment]
![image](https://user-images.githubusercontent.com/2728882/92407431-929cbf80-f108-11ea-9e32-dc75b53336d9.png)

**Comment by QuelessQuest** [comment]
Running with the foundry in-built browser while testing. Will try on my actual server with Chrome and Firefox.

Foundry v0.7.1
All other modules disabled.

Click on a Token, use any of the included transform macros, when executed token disappears. When canceled, token re-appears. Nothing shows up in the developer console.


`Radeon Pro 560X:

  Chipset Model:	Radeon Pro 560X
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Total):	4 GB
  Vendor:	AMD (0x1002)
  Device ID:	0x67ef
  Revision ID:	0x00c2
  ROM Revision:	113-C980AL-075
  VBIOS Version:	113-C97501U-005
  EFI Driver Version:	01.A1.075
  Automatic Graphics Switching:	Supported
  gMux Version:	5.0.0
  Metal:	Supported, feature set macOS GPUFamily2 v1
  Displays:
Color LCD:
  Display Type:	Built-In Retina LCD
  Resolution:	2880 x 1800 Retina
  Framebuffer Depth:	24-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	No
  Connection Type:	Internal`

**Comment by QuelessQuest** [comment]
Also happens on the server using Chrome and Firefox to connect. I'm going to guess it is more to do with running on a Mac laptop. I'll try again later on a windows box.

**Comment by Feu-Secret** [comment]
It's difficult to me to reproduce the problem... since I don't have access to a mac. I will inquire about the graphics card model.

**Comment by Feu-Secret** [comment]
Have you tried updating the GPU drivers?

**Comment by QuelessQuest** [comment]
Unfortunately, for the mac, the graphics drivers are tied into the OS. The only way to get updated drivers is to get an updated OS, which I am currently on.

I wouldn't worry about it, there are other issue with graphics and the mac using the laptop screen. If I can find my cable and connect to an external display, I a betting the issue goes away.

Don't think this is your issue to solve. But thanks for checking into it. Call it a mac thing. If I figure something out, I'll let you know.

**Comment by BoltsJ** [comment]
I'm getting this same issue on Pop_OS 20.04 and 20.10, on the electron app, Firefox and chromium.

Laptop: Pop 20.04:
Intel Graphics on latest drivers

Desktop: Pop 20.10:
Amd RX 590, latest stable drivers

**Comment by Feu-Secret** [comment]
Thank to @dev7355608, this issue should be corrected for the next release!

**Comment by dev7355608** [comment]
When v0.5.0 is released and it's still not working, let us know.
