### ISSUE TITLE
Improve MESS incompatibility for effect versus template selection

### ISSUE THREAD

**Issue by Norc** [Feu-Secret/Tokenmagic#49]
While I love the idea of the new template effects, they are overriding the animated templates I have specfically defined with MESS.

I'd like to see some compatibility settings:

1) Add an option to use MESS effects instead when a template is specifically defined for that spell - on by default?
2) Add an option to use MESS default templates instead maybe?
3) Add a way to specifically turn on the Token Magic FX as a default instead of the MESS default for a particular spell

Thanks!! I love the new shininess, but I really want my precious library of animated spell templates to still be usable.

**Comment by Feu-Secret** [comment]
Hey Norc ! 
I have an announce : Token Magic will absorb all features of Mess Moerill's Supersuite. Moerill, then, will deprecate the template part in its module. The technical parts are a bit tricky, we need just a little time to do it well. 😺

**Comment by Feu-Secret** [comment]
TMFX now supports video and texture resize!
