### ISSUE TITLE
Cannot add visual effects to templates via macros?

### ISSUE THREAD

**Issue by mbmerrill** [Feu-Secret/Tokenmagic#53]
I can't tell if I'm supposed to be able to do this or not.

From the description of this module on foundryvtt.com: "Add visual effects to templates, drawings, tokens and tiles."  This led me to believe that I could add these visual effects via macros to shapes created via Measurement Tools -> [Shape] Template.

I can use the provided macros in the compendium to add effects to tokens. However, if I select a spell template instead of a token before activating the macro, I'm not seeing anything change in the template. Are the supplied macros supposed to work with Measurement Controls -> [Shape] Templates?

**Comment by Feu-Secret** [comment]
For templates, you must create a preset in the template library, with TokenMagic.AddPreset API. This is explained in the README.
Then, the added effect can be applied with the dropbox selection in the Measured Template UI.
