### ISSUE TITLE
Shadow shouldn't move with zoom

### ISSUE THREAD

**Issue by rmasoni** [Feu-Secret/Tokenmagic#61]
Currently, the shadow filter moves when you zoom in or out. Is it possible to prevent this?

![2020-10-25 17 18 46](https://user-images.githubusercontent.com/62244/97118010-60f6ac80-16e6-11eb-96c4-e014c3a1cc1e.gif)

Also, the art becomes blurry when any filter is applied. Is this inevitable?

**Comment by Feu-Secret** [comment]
Thank for the report. The correction is a little tricky. Postponed to v0.4.6-alpha milestone.

**Comment by rmasoni** [comment]
👏
