### ISSUE TITLE
Grid squares are not highlighted for players with template has a FX effect

### ISSUE THREAD

**Issue by DarKDinDoN** [Feu-Secret/Tokenmagic#66]
Hello,

FVTT 0.7.6
5e 0.99

Applying visual effect to a template does not display the highlighted squares for the players

GM view:
![image](https://user-images.githubusercontent.com/1687854/98555726-9254a800-22a2-11eb-91e5-16657b73db8b.png)

Player view:
![image](https://user-images.githubusercontent.com/1687854/98555741-97b1f280-22a2-11eb-8136-eadb2da34e44.png)

**Comment by Feu-Secret** [comment]
Thank for the report!
