### ISSUE TITLE
ActiveEffects: macro ignored if the macro name has a space

### ISSUE THREAD

**Issue by caewok** [Feu-Secret/Tokenmagic#67]
Running Foundry 0.7.5 and Tokenmagic 0.4.4. I am trying to add an active effect that will apply a TokenMagic effect on a targeted creature. For example, electricity overlaid on a targeted token when Shocking Grasp is successfully cast.

 I can add an ActiveEffect to a spell by adding the spell to the Items Directory, and then going to the ActiveEffects tab in the spell description.  In the ActiveEffects tab, I go to the Effects tab, add a new effect, and select "Macro TokenMagic" as the Attribute Key. Then, for effect, it gives me a choice of every TokenMagic effect. If I choose an effect with a space in the name (e.g. Fairy Outline) then the TokenMagic effect is not applied when the ActiveEffect is triggered. If I choose an effect without a space (e.g. electric) than the TokenMagic effect is applied as expected. This happens for library presets and also happens for user-added presets. 

(To make the spell effect work, after adding the effect and possibly a duration, drag the spell to a character sheet. Then cast as normal. For Shocking Grasp, if the spell hits, the effect will be enabled on the target.)

**Comment by Feu-Secret** [comment]
Sorry to keep you waiting all this time. Nevertheless, it seems to me that this problem of spaces is related to the dynamic effect module. I suggest you contact its author.
