### ISSUE TITLE
Do not set resolution in FilterBlur

### ISSUE THREAD

**Issue by dev7355608** [Feu-Secret/Tokenmagic#68]
Remove the following line. It doesn't do anything anyway at the moment (?).
https://github.com/Feu-Secret/Tokenmagic/blob/b346e871add34e9bbc93336907590496bd6dc830/tokenmagic/fx/filters/FilterBlur.js#L10
If `window.devicePixelRatio > 1` and the filter's resolution is forced to 1, the quality will be negatively affected if the blur filter is applied after [this issue](https://gitlab.com/foundrynet/foundryvtt/-/issues/4176) has been resolved. It doesn't make a difference now, but I thought I should let you know right away.

**Comment by Feu-Secret** [comment]
Good catch! Thanks for the report.
