### ISSUE TITLE
[ENHANCEMENT] Allow FX to apply to templates

### ISSUE THREAD

**Issue by deurk** [Feu-Secret/Tokenmagic#7]
Would be so great to create cones of fire, circles of heal and so forth.

**Comment by Feu-Secret** [comment]
I'm working on it. For the moment, I cannot give deadlines.

**Comment by Feu-Secret** [comment]
Postponed to v0.2.2-alpha. Other features have been prioritized.

**Comment by pdf** [comment]
Looking forward to this, would allow creation of a MESS-style module that uses shaders instead of video files (using videos feels so inefficient when we're already in a GL engine)., with much greater flexibility.

**Comment by Feu-Secret** [comment]
Coming soon. I would say next weekend at worst.

**Comment by Feu-Secret** [comment]
It's hot...
![image](https://user-images.githubusercontent.com/66535080/90307034-437db900-ded3-11ea-9855-58725774768d.png)

**Comment by deurk** [comment]
OH YEAH!

**Comment by Feu-Secret** [comment]
Done !
