### ISSUE TITLE
Issue with Default Template Texture

### ISSUE THREAD

**Issue by gaggle331** [Feu-Secret/Tokenmagic#86]
I'm getting this error when trying to use tokenmagic to apply an animation to my spell. I have the texture field left blank 
```Failed to load texture /modules/tokenmagic/fx/assets/templates/black-tone-strong-opacity.png: Invalid URL```

That file location exists, and if I manually select it, the animation and texture work correctly. Is this a known issue or is there something wrong with how I have Foundry set up? I'm using the docker image and it is behind an nginx reverse proxy.

**Comment by dev7355608** [comment]
I assume it's this issue (#59). I'll make sure it's fixed in the next release.

**Comment by gaggle331** [comment]
Any idea how I might fix that issue locally (temporarily)? I was hoping to get this working for my game this week.

**Comment by dev7355608** [comment]
Either drop the route prefix if possible, or search & replace  `/modules` by `./modules` in all files of the module. Let me know if that fixes the problem.

**Comment by gaggle331** [comment]
It did not work when I replaced all instances in the module files but I made that replacement in the settings.db for the world and it seems to work now... Not sure if replacing the module files would make it work in a new world. Thanks for the temporary solution though!
