### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by PaulWRoberts** [Feu-Secret/Tokenmagic#88]
Attempting to install from Foundry Module finder will result in "Not found" error.

**Comment by zarmstrong** [comment]
Caused by **https://raw.githubusercontent.com/Feu-Secret/Tokenmagic/master/tokenmagic/module.json** te,lling foundry to download **https://github.com/Feu-Secret/Tokenmagic/releases/download/v0.4.5-alpha/Tokenmagic.zip**, which doesn't exist.

**Comment by Jonwh25** [comment]
COnfirmed bug. It doesn't install for me either.

**Comment by Feu-Secret** [comment]
Fixed!
