### ISSUE TITLE
No installation?! BUG

### ISSUE THREAD

**Issue by Flintwyrm** [Feu-Secret/Tokenmagic#89]
I went to update and the message in the image appeared. I uninstalled to see if maybe the link had changed and still I get this.

![Screenshot_1269](https://user-images.githubusercontent.com/60701064/107907291-48becd80-6f21-11eb-879a-a12df7debf3a.png)

**Comment by zarmstrong** [comment]
Dupe of #88

**Comment by FatBiscuit** [comment]
Same issue here.

**Comment by Flintwyrm** [comment]
> Dupe of #88

how do I fix this and get it back?

**Comment by Jonwh25** [comment]
> > Dupe of #88
> 
> how do I fix this and get it back?

You can manually install it back just download it here ->  https://github.com/Feu-Secret/Tokenmagic/releases/download/v0.4.4-alpha/tokenmagic.zip

We will have to wait for it to get fixed in the meantime.

**Comment by Feu-Secret** [comment]
Oops!!! Sorry! On it!

**Comment by Feu-Secret** [comment]
Fixed!
