### ISSUE TITLE
Readme without a changelog?

### ISSUE THREAD

**Issue by dmrickey** [Feu-Secret/Tokenmagic#94]
It's incredibly hard to look at the readme and know what this mod is doing. It would be nice if the changelog were separate from the readme. I can look at a change towards the top, and then keep reading towards the bottom, but the further down the page I get the less sure I am if that's a feature that's currently in the module.

What is MESS integration? Do I need MESS? Does this work beside MESS? Does it replace MESS?

**Comment by Feu-Secret** [comment]
You're right. I will create a doc and separate it from the changelog for the 0.5.1-beta release.
MESS is a delisted module. You don't need it.

**Comment by dmrickey** [comment]
Great work! This new readme is incredibly detailed. Thanks for all the work you put into it.

**Comment by Feu-Secret** [comment]
> 
> 
> Great work! This new readme is incredibly detailed. Thanks for all the work you put into it.

Thank you!
