### ISSUE TITLE
TMFX effects not turning off automatically

### ISSUE THREAD

**Issue by 8woot8** [Feu-Secret/Tokenmagic#95]
![Token Magic Issue w_DAE](https://user-images.githubusercontent.com/80236010/110276502-18020f00-7f88-11eb-8f95-90ea6cfb5a0c.PNG)

Hi, 

Attempted to utilize TMFX w/ Active Auras and DAE modules to create an aura field for paladins and certain types of spells.  Unfortunately, I'm running into an issue where the applied filtering affects are not removed when the character moves out of range of the aura (or the source moves away).  When the characters move back into range, I'm seeing a duplicating effect w/ DAE, not to mention that the filtering effects get a lil wacky when there are multiple auras.  Filtering effects have to manually removed.  Is there a way to fix this w/o having to write up a macro or manually removing the filters that TMFX creates? 

Appreciate any assistance w/ this.

**Comment by Feu-Secret** [comment]
This is done via Macro. I recommand you to subscribe to foundry vtt official discord, and ask questions to the macro-polo subgroup. You will meet fantastic peoples to help you!
