### ISSUE TITLE
It is possible to change the mirror image effect image for one different from the token? 

### ISSUE THREAD

**Issue by jacksands** [Feu-Secret/Tokenmagic#98]
It is possible to change the mirror image effect image for another? I'm trying to make a light orb orbiting the character token, I have altered a bit with that fx and succeeded in make 1 mirror image orbit the character, but I want to change that image for the orb, if an webm is possible, evem better...!!! any sugestions? ps: I'm realy bad at coding.... doing it at try and error, mostly copy paste!

**Comment by MS-PBS** [comment]
I think you'll have better luck using Kandashi's Custom Token Animations for this.
